import {
  generateTestIntents,
  generateTestPlan,
  MockAiProvider,
  type AiInvocationRecord,
} from "@testpilot/ai-core";
import { Prisma, type PrismaClient, type RiskLevel } from "@testpilot/database";
import {
  TEST_INTENT_SCHEMA_VERSION,
  validateTestIntent,
  type TestIntent,
} from "@testpilot/test-ir";
import type { GeneratePlanJob } from "../types.js";

function json(value: unknown): Prisma.InputJsonValue {
  return JSON.parse(JSON.stringify(value)) as Prisma.InputJsonValue;
}

function risk(priority: string): RiskLevel {
  switch (priority.toLowerCase()) {
    case "critical":
      return "CRITICAL";
    case "high":
      return "HIGH";
    case "low":
      return "LOW";
    default:
      return "MEDIUM";
  }
}

function safeKey(value: string, index: number): string {
  const normalized = value.toUpperCase().replace(/[^A-Z0-9_-]/g, "-");
  return (normalized || `AI-${index + 1}`).slice(0, 80);
}

function actionFromAi(
  action: { action: string; target: string; value?: string },
  baseUrl: string,
): TestIntent["actions"][number] {
  const operation = action.action.toLowerCase();
  if (operation === "navigate") {
    const path = action.target.toLowerCase().includes("login") ? "/login" : "/";
    return { type: "navigate", url: new URL(path, baseUrl).toString() };
  }
  if (operation === "fill") {
    return {
      type: "fill",
      target: { strategy: "label", value: action.target },
      value: action.value ?? "",
    };
  }
  return {
    type: "click",
    target: { strategy: "text", value: action.target },
  };
}

function intentFromAi(
  generated: {
    id: string;
    name: string;
    goal: string;
    preconditions: string[];
    actions: Array<{ action: string; target: string; value?: string }>;
    assertions: string[];
    tags: string[];
  },
  requirementKey: string | undefined,
  priority: string,
  baseUrl: string,
): TestIntent {
  return validateTestIntent({
    schemaVersion: TEST_INTENT_SCHEMA_VERSION,
    id: generated.id,
    title: generated.name,
    businessObjective: generated.goal,
    requirementRefs: requirementKey ? [requirementKey] : [],
    riskLevel: risk(priority),
    tags: generated.tags,
    preconditions: generated.preconditions,
    requiredData: {},
    environmentAssumptions: [`Application is reachable at ${baseUrl}`],
    actions: generated.actions.map((action) => actionFromAi(action, baseUrl)),
    assertions: generated.assertions.map((assertion) => ({
      type: "assertVisible" as const,
      target: { strategy: "text" as const, value: assertion },
    })),
    cleanupActions: [],
    destructive: false,
    expectedOutcome: generated.assertions.join("; "),
    traceability: {
      source: requirementKey ?? "AI-generated plan",
      notes: "Generated by the deterministic TestPilot provider; review required",
    },
  });
}

async function recordInvocation(
  database: PrismaClient,
  data: GeneratePlanJob,
  purpose: string,
  request: unknown,
  response: unknown,
  audit: AiInvocationRecord,
): Promise<void> {
  await database.aiInvocation.create({
    data: {
      workspaceId: data.workspaceId,
      projectId: data.projectId,
      createdById: data.createdById,
      provider: "MOCK",
      model: audit.model,
      purpose,
      request: json(request),
      response: json(response),
      inputTokens: audit.tokenUsage.inputTokens,
      outputTokens: audit.tokenUsage.outputTokens,
      latencyMs: audit.latencyMs,
      status: "SUCCEEDED",
      relatedType: "Project",
      relatedId: data.projectId,
    },
  });
}

export async function processGeneratePlan(
  database: PrismaClient,
  data: GeneratePlanJob,
): Promise<{ testPlanId: string; testCaseIds: string[] }> {
  const queuedPlan = data.planId
    ? await database.testPlan.findFirstOrThrow({
        where: {
          id: data.planId,
          workspaceId: data.workspaceId,
          projectId: data.projectId,
          deletedAt: null,
        },
      })
    : undefined;
  const jobData = {
    ...data,
    createdById: data.createdById ?? queuedPlan?.createdById ?? undefined,
  };
  const requirements = await database.requirement.findMany({
    where: {
      workspaceId: data.workspaceId,
      projectId: data.projectId,
      deletedAt: null,
      ...(data.requirementIds
        ? { id: { in: data.requirementIds } }
        : { status: "ACTIVE" }),
    },
    orderBy: { key: "asc" },
  });
  if (requirements.length === 0) {
    throw new Error("No active requirements were found for plan generation");
  }
  const environment = await database.environment.findFirst({
    where: { projectId: data.projectId, deletedAt: null },
    orderBy: [{ isDefault: "desc" }, { createdAt: "asc" }],
  });
  const baseUrl = environment?.baseUrl ?? process.env.DEMO_SUT_URL;
  if (!baseUrl) throw new Error("No project environment or DEMO_SUT_URL exists");

  const provider = new MockAiProvider();
  const requirementsInput = requirements
    .map(
      (item) =>
        `${item.key}: ${item.title}\n${item.description}\nAcceptance: ${JSON.stringify(item.acceptanceCriteria)}`,
    )
    .join("\n\n");
  let planAudit: AiInvocationRecord | undefined;
  const planRequest = {
    requirements: requirementsInput,
    constraints: data.includeDiscovery
      ? ["Include exploratory discovery coverage"]
      : [],
  };
  const planResult = await generateTestPlan(
    planRequest,
    { provider, onAudit: (record) => { planAudit = record; } },
  );
  if (!planAudit) throw new Error("AI plan generation did not emit audit data");
  await recordInvocation(
    database,
    jobData,
    "generateTestPlan",
    planRequest,
    planResult,
    planAudit,
  );

  let intentAudit: AiInvocationRecord | undefined;
  const intentResult = await generateTestIntents(
    {
      testPlan: JSON.stringify(planResult),
      applicationContext: `Base URL: ${baseUrl}`,
    },
    { provider, onAudit: (record) => { intentAudit = record; } },
  );
  if (!intentAudit) throw new Error("AI intent generation did not emit audit data");
  await recordInvocation(
    database,
    jobData,
    "generateTestIntents",
    { testPlan: planResult, applicationContext: { baseUrl } },
    intentResult,
    intentAudit,
  );

  const plan = queuedPlan
    ? await database.testPlan.update({
        where: { id: queuedPlan.id },
        data: {
          description: planResult.objective,
          objective: json(planResult.scope),
          status: "GENERATED",
          updatedById: jobData.createdById,
        },
      })
    : await database.testPlan.upsert({
        where: {
          projectId_name: { projectId: data.projectId, name: planResult.title },
        },
        create: {
          workspaceId: data.workspaceId,
          projectId: data.projectId,
          name: planResult.title,
          description: planResult.objective,
          objective: json(planResult.scope),
          status: "GENERATED",
          createdById: jobData.createdById,
          updatedById: jobData.createdById,
        },
        update: {
          description: planResult.objective,
          objective: json(planResult.scope),
          status: "GENERATED",
          updatedById: jobData.createdById,
          deletedAt: null,
        },
      });

  const testCaseIds: string[] = [];
  for (const [index, generated] of intentResult.intents.entries()) {
    const planned = planResult.testCases[index] ?? planResult.testCases[0]!;
    const requirement = requirements[index] ?? requirements[0];
    const intent = intentFromAi(
      generated,
      requirement?.key,
      planned.priority,
      baseUrl,
    );
    const key = safeKey(planned.id || generated.id, index);
    const testCase = await database.testCase.upsert({
      where: { projectId_key: { projectId: data.projectId, key } },
      create: {
        workspaceId: data.workspaceId,
        projectId: data.projectId,
        testPlanId: plan.id,
        requirementId: requirement?.id,
        key,
        title: generated.name,
        description: generated.goal,
        status: "GENERATED",
        riskLevel: intent.riskLevel,
        intent: json(intent),
        tags: generated.tags,
        createdById: jobData.createdById,
        updatedById: jobData.createdById,
      },
      update: {
        testPlanId: plan.id,
        requirementId: requirement?.id,
        title: generated.name,
        description: generated.goal,
        status: "GENERATED",
        riskLevel: intent.riskLevel,
        intent: json(intent),
        tags: generated.tags,
        updatedById: jobData.createdById,
        deletedAt: null,
      },
    });
    await database.testCaseVersion.upsert({
      where: {
        testCaseId_revision: {
          testCaseId: testCase.id,
          revision: testCase.currentVersion,
        },
      },
      create: {
        workspaceId: data.workspaceId,
        testCaseId: testCase.id,
        revision: testCase.currentVersion,
        title: testCase.title,
        description: testCase.description,
        status: "GENERATED",
        riskLevel: testCase.riskLevel,
        intent: json(intent),
        tags: generated.tags,
        changeSummary: "AI-generated test intent",
        createdById: jobData.createdById,
      },
      update: {
        title: testCase.title,
        description: testCase.description,
        status: "GENERATED",
        riskLevel: testCase.riskLevel,
        intent: json(intent),
        tags: generated.tags,
        compiledCode: null,
        compiledChecksum: null,
        compilerVersion: null,
        schemaVersion: null,
      },
    });
    testCaseIds.push(testCase.id);
  }
  return { testPlanId: plan.id, testCaseIds };
}
