import { createHash, randomUUID } from "node:crypto";
import { compare } from "bcryptjs";
import Fastify, {
  type FastifyRequest,
} from "fastify";
import cors from "@fastify/cors";
import jwt from "@fastify/jwt";
import swagger from "@fastify/swagger";
import swaggerUi from "@fastify/swagger-ui";
import { S3Client } from "@aws-sdk/client-s3";
import pino from "pino";
import { z, ZodError } from "zod";
import {
  ApproveTestCaseSchema,
  CreateEnvironmentSchema,
  CreateProjectSchema,
  CreateRequirementSchema,
  CreateRunSchema,
  GeneratePlanSchema,
  HealingDecisionSchema,
  ImportRequirementsSchema,
  PaginationSchema,
  SignInSchema,
  UpsertAiConfigurationSchema,
  UuidSchema,
} from "@testpilot/contracts";
import {
  Prisma,
  type PrismaClient,
  prisma as defaultPrisma,
} from "@testpilot/database";
import {
  hasPermission,
  isTerminalRunStatus,
  transitionTestCase,
  transitionTestRun,
  type Permission,
  type Role,
  type TestCaseStatus,
  type TestRunStatus,
} from "@testpilot/domain";
import {
  generateTestPlan,
  MockAiProvider,
  type AiInvocationRecord,
} from "@testpilot/ai-core";
import { SecretBox } from "@testpilot/security";
import { compileTestIntent } from "@testpilot/test-compiler";
import {
  TEST_INTENT_SCHEMA_VERSION,
  validateTestIntent,
  type TestIntent,
} from "@testpilot/test-ir";
import { readConfig, type ApiConfig } from "./config.js";
import {
  InMemoryJobQueue,
  RedisJobQueue,
  type JobQueue,
} from "./queue.js";

interface AuthToken {
  sub: string;
  sid: string;
}

interface AuthContext {
  userId: string;
  sessionId: string;
}

declare module "fastify" {
  interface FastifyRequest {
    authContext: AuthContext | null;
  }
}

class ApiError extends Error {
  constructor(
    readonly statusCode: number,
    readonly code: string,
    message: string,
  ) {
    super(message);
  }
}

export interface BuildAppOptions {
  config?: ApiConfig;
  prisma?: PrismaClient;
  queue?: JobQueue;
  logger?: ReturnType<typeof pino>;
}

const IdParams = z.object({ id: UuidSchema });
const ProjectQuery = z.object({ workspaceId: UuidSchema.optional() });
const SuiteInput = z.object({
  key: z
    .string()
    .min(2)
    .max(40)
    .regex(/^[A-Z][A-Z0-9_-]*$/)
    .optional(),
  name: z.string().min(2).max(120),
  description: z.string().max(2_000).optional(),
  testPlanId: UuidSchema.optional(),
  testCaseIds: z.array(UuidSchema).default([]),
});
const RequirementInput = CreateRequirementSchema.extend({
  key: z
    .string()
    .min(2)
    .max(40)
    .regex(/^[A-Z][A-Z0-9_-]*$/)
    .optional(),
  acceptanceCriteria: z.array(z.string().min(1)).default([]),
});
const CreateProjectInput = CreateProjectSchema.extend({
  workspaceId: UuidSchema,
});
const HealingDecisionInput = HealingDecisionSchema.or(
  z.object({ note: z.string().max(2_000).optional() }),
);

function tokenHash(value: string): string {
  return createHash("sha256").update(value).digest("hex");
}

function json(value: unknown): Prisma.InputJsonValue {
  return value as Prisma.InputJsonValue;
}

function riskFromPriority(
  priority: "critical" | "high" | "medium" | "low",
): "CRITICAL" | "HIGH" | "MEDIUM" | "LOW" {
  return priority.toUpperCase() as "CRITICAL" | "HIGH" | "MEDIUM" | "LOW";
}

function aiProviderKind(
  provider: z.infer<typeof UpsertAiConfigurationSchema>["provider"],
): "OPENAI" | "ANTHROPIC" | "GOOGLE" | "AZURE_OPENAI" | "MOCK" {
  const providers = {
    openai: "OPENAI",
    anthropic: "ANTHROPIC",
    gemini: "GOOGLE",
    openai_compatible: "AZURE_OPENAI",
    mock: "MOCK",
  } as const;
  return providers[provider];
}

function generatedIntent(
  testCase: {
    id: string;
    title: string;
    priority: "critical" | "high" | "medium" | "low";
    type: string;
    preconditions: string[];
    steps: string[];
    expectedResult: string;
  },
  objective: string,
  requirementKeys: string[],
): TestIntent {
  return validateTestIntent({
    schemaVersion: TEST_INTENT_SCHEMA_VERSION,
    id: testCase.id,
    title: testCase.title,
    businessObjective: objective,
    requirementRefs: requirementKeys,
    riskLevel: riskFromPriority(testCase.priority),
    tags: ["ai-generated", testCase.type],
    preconditions: testCase.preconditions,
    requiredData: {},
    environmentAssumptions: [],
    actions: [
      {
        type: "navigate",
        url: "/",
        description: testCase.steps.join(" → "),
      },
    ],
    assertions: [
      {
        type: "assertText",
        target: { strategy: "css", value: "body" },
        expected: testCase.expectedResult,
      },
    ],
    cleanupActions: [],
    destructive: false,
    expectedOutcome: testCase.expectedResult,
    traceability: {
      source: requirementKeys.join(","),
      notes: "Generated by TestPilot AI; locators require validation before approval.",
    },
  });
}

function corsOrigins(config: ApiConfig): string[] {
  return config.CORS_ORIGIN.split(",")
    .map((origin) => origin.trim())
    .filter(Boolean);
}

export async function buildApp(
  options: BuildAppOptions = {},
) {
  const config = options.config ?? readConfig();
  const db = options.prisma ?? defaultPrisma;
  const ownsQueue = options.queue === undefined;
  const queue = options.queue ?? new RedisJobQueue(config.REDIS_URL);
  const logger =
    options.logger ??
    pino({
      level: config.LOG_LEVEL,
      redact: {
        paths: [
          "req.headers.authorization",
          "req.headers.cookie",
          "password",
          "apiKey",
          "*.password",
          "*.apiKey",
        ],
        censor: "[REDACTED]",
      },
    });
  const s3 = new S3Client({
    region: config.S3_REGION,
    ...(config.S3_ENDPOINT
      ? {
          endpoint: config.S3_ENDPOINT,
          forcePathStyle: config.S3_FORCE_PATH_STYLE,
        }
      : {}),
    ...(config.S3_ACCESS_KEY_ID && config.S3_SECRET_ACCESS_KEY
      ? {
          credentials: {
            accessKeyId: config.S3_ACCESS_KEY_ID,
            secretAccessKey: config.S3_SECRET_ACCESS_KEY,
          },
        }
      : {}),
  });
  const app = Fastify({
    loggerInstance: logger,
    trustProxy: true,
    genReqId(request) {
      const correlationId = request.headers["x-correlation-id"];
      return typeof correlationId === "string" &&
        /^[\w./-]{1,128}$/.test(correlationId)
        ? correlationId
        : randomUUID();
    },
  });
  app.decorateRequest("authContext", null);

  const metrics = {
    requests: new Map<string, number>(),
    startedAt: Date.now(),
  };

  await app.register(cors, {
    origin(origin, callback) {
      if (!origin || corsOrigins(config).includes(origin)) callback(null, true);
      else callback(new Error("Origin is not allowed"), false);
    },
    credentials: true,
    exposedHeaders: ["x-correlation-id"],
  });
  await app.register(jwt, { secret: config.JWT_SECRET });
  await app.register(swagger, {
    openapi: {
      info: {
        title: "TestPilot AI API",
        description: "Multi-tenant AI-assisted automated testing API",
        version: "1.0.0",
      },
      servers: [{ url: config.API_PUBLIC_URL }],
      components: {
        securitySchemes: {
          bearerAuth: { type: "http", scheme: "bearer", bearerFormat: "JWT" },
        },
      },
      security: [{ bearerAuth: [] }],
    },
  });
  await app.register(swaggerUi, {
    routePrefix: "/docs",
    uiConfig: { docExpansion: "list", deepLinking: true },
  });

  app.addHook("onRequest", async (request, reply) => {
    reply.header("x-correlation-id", request.id);
  });
  app.addHook("onResponse", async (request, reply) => {
    const key = `${request.method} ${request.routeOptions.url} ${reply.statusCode}`;
    metrics.requests.set(key, (metrics.requests.get(key) ?? 0) + 1);
  });

  async function authenticate(request: FastifyRequest): Promise<void> {
    let token: AuthToken;
    try {
      token = await request.jwtVerify<AuthToken>();
    } catch {
      throw new ApiError(401, "UNAUTHENTICATED", "Authentication is required");
    }
    const session = await db.session.findFirst({
      where: {
        tokenHash: tokenHash(token.sid),
        userId: token.sub,
        revokedAt: null,
        expiresAt: { gt: new Date() },
        user: { active: true, deletedAt: null },
      },
      select: { id: true, userId: true },
    });
    if (!session) {
      throw new ApiError(401, "SESSION_INVALID", "Session is invalid or expired");
    }
    request.authContext = { userId: session.userId, sessionId: token.sid };
  }

  function auth(request: FastifyRequest): AuthContext {
    if (!request.authContext) {
      throw new ApiError(401, "UNAUTHENTICATED", "Authentication is required");
    }
    return request.authContext;
  }

  async function workspaceAccess(
    request: FastifyRequest,
    workspaceId: string,
    permission?: Permission,
  ): Promise<{ workspaceId: string; role: Role }> {
    const membership = await db.membership.findFirst({
      where: {
        workspaceId,
        userId: auth(request).userId,
        deletedAt: null,
        workspace: { deletedAt: null },
      },
      select: { workspaceId: true, role: true },
    });
    if (!membership) {
      throw new ApiError(404, "NOT_FOUND", "Workspace was not found");
    }
    if (permission && !hasPermission(membership.role as Role, permission)) {
      throw new ApiError(403, "FORBIDDEN", `Permission ${permission} is required`);
    }
    return { workspaceId: membership.workspaceId, role: membership.role as Role };
  }

  async function projectAccess(
    request: FastifyRequest,
    projectId: string,
    permission: Permission = "project:read",
  ): Promise<{ projectId: string; workspaceId: string; role: Role }> {
    const project = await db.project.findFirst({
      where: {
        id: projectId,
        deletedAt: null,
        workspace: {
          deletedAt: null,
          memberships: {
            some: { userId: auth(request).userId, deletedAt: null },
          },
        },
      },
      select: {
        id: true,
        workspaceId: true,
        workspace: {
          select: {
            memberships: {
              where: { userId: auth(request).userId, deletedAt: null },
              select: { role: true },
              take: 1,
            },
          },
        },
      },
    });
    const membership = project?.workspace.memberships[0];
    if (!project || !membership) {
      throw new ApiError(404, "NOT_FOUND", "Project was not found");
    }
    if (!hasPermission(membership.role as Role, permission)) {
      throw new ApiError(403, "FORBIDDEN", `Permission ${permission} is required`);
    }
    return {
      projectId: project.id,
      workspaceId: project.workspaceId,
      role: membership.role as Role,
    };
  }

  async function testCaseAccess(
    request: FastifyRequest,
    testCaseId: string,
    permission: Permission = "project:read",
  ) {
    const testCase = await db.testCase.findFirst({
      where: {
        id: testCaseId,
        deletedAt: null,
        project: {
          deletedAt: null,
          workspace: {
            memberships: {
              some: { userId: auth(request).userId, deletedAt: null },
            },
          },
        },
      },
    });
    if (!testCase) {
      throw new ApiError(404, "NOT_FOUND", "Test case was not found");
    }
    await projectAccess(request, testCase.projectId, permission);
    return testCase;
  }

  async function audit(
    request: FastifyRequest,
    workspaceId: string,
    action: string,
    entityType: string,
    entityId?: string,
    metadata: Record<string, unknown> = {},
  ): Promise<void> {
    await db.auditEvent.create({
      data: {
        workspaceId,
        actorId: auth(request).userId,
        action,
        entityType,
        ...(entityId ? { entityId } : {}),
        metadata: json({ ...metadata, correlationId: request.id }),
        ipAddress: request.ip,
        userAgent: request.headers["user-agent"],
      },
    });
  }

  app.get("/health", { schema: { security: [] } }, async () => ({
    status: "ok",
    service: "@testpilot/api",
    uptimeSeconds: Math.floor(process.uptime()),
  }));

  app.get("/ready", { schema: { security: [] } }, async (_request, reply) => {
    try {
      await Promise.all([db.$queryRaw`SELECT 1`, queue.ping()]);
      return { status: "ready", database: "ok", redis: "ok" };
    } catch (error) {
      reply.code(503);
      return {
        status: "not_ready",
        error: error instanceof Error ? error.message : "Dependency check failed",
      };
    }
  });

  app.get("/metrics", { schema: { security: [] } }, async (_request, reply) => {
    const lines = [
      "# HELP testpilot_api_uptime_seconds Process uptime.",
      "# TYPE testpilot_api_uptime_seconds gauge",
      `testpilot_api_uptime_seconds ${(Date.now() - metrics.startedAt) / 1_000}`,
      "# HELP testpilot_api_http_requests_total HTTP requests processed.",
      "# TYPE testpilot_api_http_requests_total counter",
    ];
    for (const [key, count] of metrics.requests) {
      const [method, ...rest] = key.split(" ");
      const status = rest.pop() ?? "unknown";
      const route = rest.join(" ");
      lines.push(
        `testpilot_api_http_requests_total{method="${method}",route="${route}",status="${status}"} ${count}`,
      );
    }
    return reply.type("text/plain; version=0.0.4").send(`${lines.join("\n")}\n`);
  });

  app.post(
    "/api/v1/auth/sign-in",
    { schema: { security: [], tags: ["auth"] } },
    async (request, reply) => {
      const input = SignInSchema.parse(request.body);
      const user = await db.user.findFirst({
        where: {
          email: input.email.toLowerCase(),
          active: true,
          deletedAt: null,
        },
        include: {
          memberships: {
            where: { deletedAt: null, workspace: { deletedAt: null } },
            select: { workspaceId: true, role: true },
            orderBy: { createdAt: "asc" },
          },
        },
      });
      if (!user || !(await compare(input.password, user.passwordHash))) {
        throw new ApiError(401, "INVALID_CREDENTIALS", "Email or password is invalid");
      }
      const sessionId = randomUUID();
      const expiresAt = new Date(Date.now() + config.SESSION_TTL_SECONDS * 1_000);
      await db.session.create({
        data: {
          tokenHash: tokenHash(sessionId),
          userId: user.id,
          workspaceId: user.memberships[0]?.workspaceId,
          expiresAt,
          ipAddress: request.ip,
          userAgent: request.headers["user-agent"],
        },
      });
      const accessToken = app.jwt.sign(
        { sub: user.id, sid: sessionId },
        { expiresIn: config.SESSION_TTL_SECONDS },
      );
      return reply.code(200).send({
        accessToken,
        tokenType: "Bearer",
        expiresAt,
        user: {
          id: user.id,
          email: user.email,
          displayName: user.displayName,
          memberships: user.memberships,
        },
      });
    },
  );

  app.post(
    "/api/v1/auth/sign-out",
    { preHandler: authenticate, schema: { tags: ["auth"] } },
    async (request, reply) => {
      await db.session.updateMany({
        where: {
          tokenHash: tokenHash(auth(request).sessionId),
          userId: auth(request).userId,
          revokedAt: null,
        },
        data: { revokedAt: new Date() },
      });
      return reply.code(204).send();
    },
  );

  app.get(
    "/api/v1/auth/me",
    { preHandler: authenticate, schema: { tags: ["auth"] } },
    async (request) => {
      const user = await db.user.findFirst({
        where: { id: auth(request).userId, active: true, deletedAt: null },
        select: {
          id: true,
          email: true,
          displayName: true,
          memberships: {
            where: { deletedAt: null, workspace: { deletedAt: null } },
            select: {
              id: true,
              role: true,
              workspace: { select: { id: true, key: true, name: true, slug: true } },
            },
          },
        },
      });
      if (!user) throw new ApiError(404, "NOT_FOUND", "User was not found");
      return user;
    },
  );

  app.get(
    "/api/v1/workspaces",
    { preHandler: authenticate, schema: { tags: ["workspaces"] } },
    async (request) =>
      db.workspace.findMany({
        where: {
          deletedAt: null,
          memberships: {
            some: { userId: auth(request).userId, deletedAt: null },
          },
        },
        include: {
          memberships: {
            where: { userId: auth(request).userId, deletedAt: null },
            select: { role: true },
          },
          _count: { select: { projects: true, memberships: true } },
        },
        orderBy: { name: "asc" },
      }),
  );

  app.get(
    "/api/v1/projects",
    { preHandler: authenticate, schema: { tags: ["projects"] } },
    async (request) => {
      const query = ProjectQuery.parse(request.query);
      if (query.workspaceId) await workspaceAccess(request, query.workspaceId);
      return db.project.findMany({
        where: {
          deletedAt: null,
          ...(query.workspaceId ? { workspaceId: query.workspaceId } : {}),
          workspace: {
            memberships: {
              some: { userId: auth(request).userId, deletedAt: null },
            },
          },
        },
        include: {
          workspace: { select: { id: true, name: true, key: true } },
          _count: {
            select: {
              requirements: true,
              testCases: true,
              testSuites: true,
              testRuns: true,
            },
          },
        },
        orderBy: { updatedAt: "desc" },
      });
    },
  );

  app.post(
    "/api/v1/projects",
    { preHandler: authenticate, schema: { tags: ["projects"] } },
    async (request, reply) => {
      const input = CreateProjectInput.parse(request.body);
      await workspaceAccess(request, input.workspaceId, "project:create");
      const project = await db.$transaction(async (tx) => {
        const created = await tx.project.create({
          data: {
            workspaceId: input.workspaceId,
            key: input.key,
            name: input.name,
            description: input.description,
            createdById: auth(request).userId,
            updatedById: auth(request).userId,
          },
        });
        await tx.auditEvent.create({
          data: {
            workspaceId: input.workspaceId,
            actorId: auth(request).userId,
            action: "project.created",
            entityType: "Project",
            entityId: created.id,
            metadata: json({ correlationId: request.id }),
            ipAddress: request.ip,
            userAgent: request.headers["user-agent"],
          },
        });
        return created;
      });
      return reply.code(201).send(project);
    },
  );

  app.get(
    "/api/v1/projects/:id",
    { preHandler: authenticate, schema: { tags: ["projects"] } },
    async (request) => {
      const { id } = IdParams.parse(request.params);
      const access = await projectAccess(request, id);
      return db.project.findFirstOrThrow({
        where: { id, workspaceId: access.workspaceId, deletedAt: null },
        include: {
          workspace: { select: { id: true, key: true, name: true } },
          _count: {
            select: {
              requirements: true,
              environments: true,
              testPlans: true,
              testCases: true,
              testSuites: true,
              testRuns: true,
            },
          },
        },
      });
    },
  );

  app.get(
    "/api/v1/projects/:id/overview",
    { preHandler: authenticate, schema: { tags: ["projects"] } },
    async (request) => {
      const { id } = IdParams.parse(request.params);
      const access = await projectAccess(request, id);
      const [counts, runs, statusCounts, pendingHealing] = await Promise.all([
        db.project.findFirstOrThrow({
          where: { id, workspaceId: access.workspaceId, deletedAt: null },
          select: {
            id: true,
            name: true,
            _count: {
              select: {
                requirements: true,
                environments: true,
                testCases: true,
                testSuites: true,
              },
            },
          },
        }),
        db.testRun.findMany({
          where: { projectId: id, workspaceId: access.workspaceId },
          orderBy: { createdAt: "desc" },
          take: 10,
        }),
        db.testCase.groupBy({
          by: ["status"],
          where: { projectId: id, workspaceId: access.workspaceId, deletedAt: null },
          _count: true,
        }),
        db.healingProposal.count({
          where: {
            projectId: id,
            workspaceId: access.workspaceId,
            status: "PENDING",
          },
        }),
      ]);
      const totals = runs.reduce(
        (value, run) => ({
          passed: value.passed + run.passedTests,
          failed: value.failed + run.failedTests,
          skipped: value.skipped + run.skippedTests,
          total: value.total + run.totalTests,
        }),
        { passed: 0, failed: 0, skipped: 0, total: 0 },
      );
      return {
        project: counts,
        recentRuns: runs,
        testCasesByStatus: Object.fromEntries(
          statusCounts.map((item) => [item.status, item._count]),
        ),
        pendingHealing,
        passRate: totals.total > 0 ? totals.passed / totals.total : null,
        totals,
      };
    },
  );

  app.get(
    "/api/v1/projects/:id/requirements",
    { preHandler: authenticate, schema: { tags: ["requirements"] } },
    async (request) => {
      const { id } = IdParams.parse(request.params);
      const access = await projectAccess(request, id);
      return db.requirement.findMany({
        where: { projectId: id, workspaceId: access.workspaceId, deletedAt: null },
        include: { _count: { select: { testCases: true } } },
        orderBy: { updatedAt: "desc" },
      });
    },
  );

  app.post(
    "/api/v1/projects/:id/requirements",
    { preHandler: authenticate, schema: { tags: ["requirements"] } },
    async (request, reply) => {
      const { id } = IdParams.parse(request.params);
      const input = RequirementInput.parse(request.body);
      const access = await projectAccess(request, id, "requirement:manage");
      const key = input.key ?? `REQ-${Date.now().toString(36).toUpperCase()}`;
      const requirement = await db.$transaction(async (tx) => {
        const created = await tx.requirement.create({
          data: {
            workspaceId: access.workspaceId,
            projectId: id,
            key,
            title: input.title,
            description: input.description,
            acceptanceCriteria: input.acceptanceCriteria,
            riskLevel: input.criticality,
            createdById: auth(request).userId,
            updatedById: auth(request).userId,
          },
        });
        await tx.requirementVersion.create({
          data: {
            workspaceId: access.workspaceId,
            requirementId: created.id,
            revision: 1,
            title: created.title,
            description: created.description,
            acceptanceCriteria: input.acceptanceCriteria,
            riskLevel: created.riskLevel,
            changeSummary: "Initial version",
            createdById: auth(request).userId,
          },
        });
        return created;
      });
      await audit(
        request,
        access.workspaceId,
        "requirement.created",
        "Requirement",
        requirement.id,
      );
      return reply.code(201).send(requirement);
    },
  );

  app.post(
    "/api/v1/projects/:id/requirements/import",
    { preHandler: authenticate, schema: { tags: ["requirements"] } },
    async (request, reply) => {
      const { id } = IdParams.parse(request.params);
      const input = ImportRequirementsSchema.parse(request.body);
      const access = await projectAccess(request, id, "requirement:manage");
      let entries: Array<{
        title: string;
        description: string;
        acceptanceCriteria?: string[];
        riskLevel?: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
      }>;
      if (input.format === "JSON") {
        let parsed: unknown;
        try {
          parsed = JSON.parse(input.content);
        } catch {
          throw new ApiError(400, "INVALID_JSON", "Requirement JSON is invalid");
        }
        entries = z
          .array(
            z.object({
              title: z.string().min(1),
              description: z.string().min(1),
              acceptanceCriteria: z.array(z.string()).optional(),
              riskLevel: z.enum(["LOW", "MEDIUM", "HIGH", "CRITICAL"]).optional(),
            }),
          )
          .parse(parsed);
      } else {
        entries = input.content
          .split(/\n\s*\n/)
          .map((block) => block.trim())
          .filter(Boolean)
          .map((block) => {
            const [first, ...rest] = block.split("\n");
            return {
              title: (first ?? "Imported requirement").replace(/^#+\s*/, ""),
              description: rest.join("\n").trim() || first || "Imported requirement",
            };
          });
      }
      if (entries.length === 0) {
        throw new ApiError(400, "EMPTY_IMPORT", "No requirements were found");
      }
      const importId = Date.now().toString(36).toUpperCase();
      const created = await db.$transaction(
        entries.map((entry, index) =>
          db.requirement.create({
            data: {
              workspaceId: access.workspaceId,
              projectId: id,
              key: `REQ-${importId}-${index + 1}`,
              title: entry.title,
              description: entry.description,
              acceptanceCriteria: entry.acceptanceCriteria ?? [],
              riskLevel: entry.riskLevel ?? "MEDIUM",
              createdById: auth(request).userId,
              updatedById: auth(request).userId,
              versions: {
                create: {
                  workspaceId: access.workspaceId,
                  revision: 1,
                  title: entry.title,
                  description: entry.description,
                  acceptanceCriteria: entry.acceptanceCriteria ?? [],
                  riskLevel: entry.riskLevel ?? "MEDIUM",
                  changeSummary: `Imported from ${input.format}`,
                  createdById: auth(request).userId,
                },
              },
            },
          }),
        ),
      );
      await audit(request, access.workspaceId, "requirements.imported", "Project", id, {
        count: created.length,
        format: input.format,
      });
      return reply.code(201).send({ count: created.length, requirements: created });
    },
  );

  app.get(
    "/api/v1/projects/:id/environments",
    { preHandler: authenticate, schema: { tags: ["environments"] } },
    async (request) => {
      const { id } = IdParams.parse(request.params);
      const access = await projectAccess(request, id);
      return db.environment.findMany({
        where: { projectId: id, workspaceId: access.workspaceId, deletedAt: null },
        orderBy: [{ isDefault: "desc" }, { name: "asc" }],
      });
    },
  );

  app.post(
    "/api/v1/projects/:id/environments",
    { preHandler: authenticate, schema: { tags: ["environments"] } },
    async (request, reply) => {
      const { id } = IdParams.parse(request.params);
      const input = CreateEnvironmentSchema.parse(request.body);
      const access = await projectAccess(request, id, "environment:manage");
      const environment = await db.environment.create({
        data: {
          workspaceId: access.workspaceId,
          projectId: id,
          name: input.name,
          kind: input.kind,
          baseUrl: input.baseUrl,
          config: json({
            apiBaseUrl: input.apiBaseUrl,
            allowedDomains: input.allowedDomains,
            authStrategy: input.authStrategy,
            browserProjects: input.browserProjects,
            parallelismLimit: input.parallelismLimit,
            timeoutMs: input.timeoutMs,
            allowDestructiveTests: input.allowDestructiveTests,
          }),
          createdById: auth(request).userId,
          updatedById: auth(request).userId,
        },
      });
      await audit(
        request,
        access.workspaceId,
        "environment.created",
        "Environment",
        environment.id,
      );
      return reply.code(201).send(environment);
    },
  );

  app.get(
    "/api/v1/projects/:id/schedules",
    { preHandler: authenticate, schema: { tags: ["schedules"] } },
    async (request) => {
      const { id } = IdParams.parse(request.params);
      const access = await projectAccess(request, id);
      const items = await db.schedule.findMany({
        where: { projectId: id, workspaceId: access.workspaceId, deletedAt: null },
        include: {
          testSuite: { select: { id: true, name: true } },
          environment: { select: { id: true, name: true } },
        },
        orderBy: [{ enabled: "desc" }, { name: "asc" }],
      });
      return { items };
    },
  );

  app.post(
    "/api/v1/projects/:id/test-plans/generate",
    { preHandler: authenticate, schema: { tags: ["test-plans"] } },
    async (request, reply) => {
      const { id } = IdParams.parse(request.params);
      const input = GeneratePlanSchema.parse(request.body);
      const access = await projectAccess(request, id, "test:generate");
      const requirements = await db.requirement.findMany({
        where: {
          id: { in: input.requirementIds },
          projectId: id,
          workspaceId: access.workspaceId,
          deletedAt: null,
        },
      });
      if (requirements.length !== input.requirementIds.length) {
        throw new ApiError(
          400,
          "INVALID_REQUIREMENTS",
          "One or more requirements do not belong to this project",
        );
      }
      const suffix = randomUUID().slice(0, 8);
      if (config.AI_DEFAULT_PROVIDER.toLowerCase() !== "mock") {
        const plan = await db.testPlan.create({
          data: {
            workspaceId: access.workspaceId,
            projectId: id,
            name: `AI plan ${suffix}`,
            description: "Queued for AI generation",
            objective: json({ requirementIds: input.requirementIds }),
            status: "QUEUED",
            createdById: auth(request).userId,
            updatedById: auth(request).userId,
          },
        });
        await queue.add(
          "generate-plan",
          {
            planId: plan.id,
            projectId: id,
            workspaceId: access.workspaceId,
            requirementIds: input.requirementIds,
            includeDiscovery: input.includeDiscovery,
            correlationId: request.id,
          },
          plan.id,
        );
        await audit(request, access.workspaceId, "test_plan.queued", "TestPlan", plan.id);
        return reply.code(202).send(plan);
      }

      const provider = new MockAiProvider({ modelId: config.AI_DEFAULT_MODEL });
      const result = await generateTestPlan(
        {
          requirements: requirements
            .map(
              (item) =>
                `${item.key}: ${item.title}\n${item.description}\nAcceptance criteria: ${JSON.stringify(item.acceptanceCriteria)}`,
            )
            .join("\n\n"),
          constraints: input.includeDiscovery ? ["Include discovery coverage"] : [],
        },
        {
          provider,
          modelId: config.AI_DEFAULT_MODEL,
          correlationId: request.id,
          onAudit: async (record: AiInvocationRecord) => {
            await db.aiInvocation.create({
              data: {
                workspaceId: access.workspaceId,
                projectId: id,
                provider: "MOCK",
                model: record.model,
                purpose: "generate-plan",
                request: json({
                  requirementIds: input.requirementIds,
                  promptVersion: record.promptVersion,
                  correlationId: record.correlationId,
                }),
                response: json({
                  validationOk: record.validationOk,
                  redacted: record.redacted,
                }),
                inputTokens: record.tokenUsage.inputTokens,
                outputTokens: record.tokenUsage.outputTokens,
                latencyMs: record.latencyMs,
                status: "SUCCEEDED",
                createdById: auth(request).userId,
              },
            });
          },
        },
      );
      const requirementKeys = requirements.map((item) => item.key);
      const plan = await db.$transaction(async (tx) => {
        const createdPlan = await tx.testPlan.create({
          data: {
            workspaceId: access.workspaceId,
            projectId: id,
            name: `${result.title} ${suffix}`,
            description: result.objective,
            objective: json({
              objective: result.objective,
              scope: result.scope,
              requirementIds: input.requirementIds,
            }),
            status: "GENERATED",
            createdById: auth(request).userId,
            updatedById: auth(request).userId,
          },
        });
        for (const [index, generated] of result.testCases.entries()) {
          const intent = generatedIntent(
            generated,
            result.objective,
            requirementKeys,
          );
          const testCase = await tx.testCase.create({
            data: {
              workspaceId: access.workspaceId,
              projectId: id,
              testPlanId: createdPlan.id,
              requirementId:
                requirements.length === 1 ? requirements[0]?.id : undefined,
              key: `AI-${suffix.toUpperCase()}-${index + 1}`,
              title: generated.title,
              description: generated.expectedResult,
              status: "GENERATED",
              riskLevel: riskFromPriority(generated.priority),
              intent: json(intent),
              tags: json(["ai-generated", generated.type]),
              createdById: auth(request).userId,
              updatedById: auth(request).userId,
              versions: {
                create: {
                  workspaceId: access.workspaceId,
                  revision: 1,
                  title: generated.title,
                  description: generated.expectedResult,
                  status: "GENERATED",
                  riskLevel: riskFromPriority(generated.priority),
                  intent: json(intent),
                  tags: json(["ai-generated", generated.type]),
                  changeSummary: "Generated by AI",
                  createdById: auth(request).userId,
                },
              },
            },
          });
          await tx.auditEvent.create({
            data: {
              workspaceId: access.workspaceId,
              actorId: auth(request).userId,
              action: "test_case.generated",
              entityType: "TestCase",
              entityId: testCase.id,
              metadata: json({ correlationId: request.id, planId: createdPlan.id }),
            },
          });
        }
        return tx.testPlan.findUniqueOrThrow({
          where: { id: createdPlan.id },
          include: { testCases: true },
        });
      });
      return reply.code(201).send(plan);
    },
  );

  app.get(
    "/api/v1/projects/:id/test-plans",
    { preHandler: authenticate, schema: { tags: ["test-plans"] } },
    async (request) => {
      const { id } = IdParams.parse(request.params);
      const access = await projectAccess(request, id);
      return db.testPlan.findMany({
        where: { projectId: id, workspaceId: access.workspaceId, deletedAt: null },
        include: { _count: { select: { testCases: true, testSuites: true } } },
        orderBy: { createdAt: "desc" },
      });
    },
  );

  app.get(
    "/api/v1/projects/:id/test-cases",
    { preHandler: authenticate, schema: { tags: ["test-cases"] } },
    async (request) => {
      const { id } = IdParams.parse(request.params);
      const access = await projectAccess(request, id);
      const query = z
        .object({
          status: z
            .enum([
              "DRAFT",
              "GENERATED",
              "VALIDATED",
              "APPROVED",
              "ACTIVE",
              "DISABLED",
              "ARCHIVED",
            ])
            .optional(),
        })
        .merge(PaginationSchema)
        .parse(request.query);
      const where = {
        projectId: id,
        workspaceId: access.workspaceId,
        deletedAt: null,
        ...(query.status ? { status: query.status } : {}),
      };
      const [items, total] = await Promise.all([
        db.testCase.findMany({
          where,
          include: {
            requirement: { select: { id: true, key: true, title: true } },
            testPlan: { select: { id: true, name: true } },
          },
          skip: ((query.page ?? 1) - 1) * (query.pageSize ?? 20),
          take: query.pageSize ?? 20,
          orderBy: { updatedAt: "desc" },
        }),
        db.testCase.count({ where }),
      ]);
      return { items, total, page: query.page, pageSize: query.pageSize };
    },
  );

  app.get(
    "/api/v1/test-cases/:id",
    { preHandler: authenticate, schema: { tags: ["test-cases"] } },
    async (request) => {
      const { id } = IdParams.parse(request.params);
      const testCase = await testCaseAccess(request, id);
      return db.testCase.findFirstOrThrow({
        where: { id, workspaceId: testCase.workspaceId, deletedAt: null },
        include: {
          versions: { orderBy: { revision: "desc" } },
          requirement: true,
          testPlan: true,
        },
      });
    },
  );

  app.post(
    "/api/v1/test-cases/:id/validate",
    { preHandler: authenticate, schema: { tags: ["test-cases"] } },
    async (request) => {
      const { id } = IdParams.parse(request.params);
      const testCase = await testCaseAccess(request, id, "test:generate");
      validateTestIntent(testCase.intent);
      let nextStatus = testCase.status;
      if (testCase.status === "DRAFT" || testCase.status === "GENERATED") {
        nextStatus = transitionTestCase(
          testCase.status as TestCaseStatus,
          "VALIDATED",
        ) as typeof testCase.status;
      }
      const updated = await db.$transaction(async (tx) => {
        const value = await tx.testCase.update({
          where: { id },
          data: {
            status: nextStatus,
            updatedById: auth(request).userId,
            version: { increment: 1 },
          },
        });
        await tx.testCaseVersion.updateMany({
          where: { testCaseId: id, revision: testCase.currentVersion },
          data: { status: nextStatus },
        });
        return value;
      });
      await audit(
        request,
        testCase.workspaceId,
        "test_case.validated",
        "TestCase",
        id,
      );
      return { testCase: updated, valid: true };
    },
  );

  app.post(
    "/api/v1/test-cases/:id/approve",
    { preHandler: authenticate, schema: { tags: ["test-cases"] } },
    async (request) => {
      const { id } = IdParams.parse(request.params);
      const input = ApproveTestCaseSchema.parse(request.body ?? {});
      const testCase = await testCaseAccess(request, id, "test:approve");
      validateTestIntent(testCase.intent);
      const status = transitionTestCase(
        testCase.status as TestCaseStatus,
        "APPROVED",
      ) as typeof testCase.status;
      const updated = await db.$transaction(async (tx) => {
        const value = await tx.testCase.update({
          where: { id },
          data: {
            status,
            updatedById: auth(request).userId,
            version: { increment: 1 },
          },
        });
        await tx.testCaseVersion.updateMany({
          where: { testCaseId: id, revision: testCase.currentVersion },
          data: {
            status,
            changeSummary: input.note ?? "Approved",
          },
        });
        return value;
      });
      await audit(
        request,
        testCase.workspaceId,
        "test_case.approved",
        "TestCase",
        id,
        { note: input.note },
      );
      return updated;
    },
  );

  app.post(
    "/api/v1/test-cases/:id/compile",
    { preHandler: authenticate, schema: { tags: ["test-cases"] } },
    async (request) => {
      const { id } = IdParams.parse(request.params);
      const testCase = await testCaseAccess(request, id, "test:generate");
      const result = compileTestIntent(testCase.intent);
      const version = await db.testCaseVersion.upsert({
        where: {
          testCaseId_revision: {
            testCaseId: testCase.id,
            revision: testCase.currentVersion,
          },
        },
        create: {
          workspaceId: testCase.workspaceId,
          testCaseId: testCase.id,
          revision: testCase.currentVersion,
          title: testCase.title,
          description: testCase.description,
          status: testCase.status,
          riskLevel: testCase.riskLevel,
          intent: testCase.intent as Prisma.InputJsonValue,
          tags: testCase.tags as Prisma.InputJsonValue,
          compiledCode: result.code,
          compiledChecksum: result.checksum,
          compilerVersion: result.compilerVersion,
          schemaVersion: result.schemaVersion,
          changeSummary: "Compiled",
          createdById: auth(request).userId,
        },
        update: {
          compiledCode: result.code,
          compiledChecksum: result.checksum,
          compilerVersion: result.compilerVersion,
          schemaVersion: result.schemaVersion,
        },
      });
      await audit(
        request,
        testCase.workspaceId,
        "test_case.compiled",
        "TestCase",
        id,
        { checksum: result.checksum, versionId: version.id },
      );
      return result;
    },
  );

  app.get(
    "/api/v1/projects/:id/suites",
    { preHandler: authenticate, schema: { tags: ["suites"] } },
    async (request) => {
      const { id } = IdParams.parse(request.params);
      const access = await projectAccess(request, id);
      return db.testSuite.findMany({
        where: { projectId: id, workspaceId: access.workspaceId, deletedAt: null },
        include: {
          items: {
            orderBy: { position: "asc" },
            include: {
              testCase: {
                select: { id: true, key: true, title: true, status: true },
              },
            },
          },
        },
        orderBy: { updatedAt: "desc" },
      });
    },
  );

  app.post(
    "/api/v1/projects/:id/suites",
    { preHandler: authenticate, schema: { tags: ["suites"] } },
    async (request, reply) => {
      const { id } = IdParams.parse(request.params);
      const input = SuiteInput.parse(request.body);
      const access = await projectAccess(request, id, "test:generate");
      const caseCount = await db.testCase.count({
        where: {
          id: { in: input.testCaseIds },
          projectId: id,
          workspaceId: access.workspaceId,
          deletedAt: null,
        },
      });
      if (caseCount !== input.testCaseIds.length) {
        throw new ApiError(
          400,
          "INVALID_TEST_CASES",
          "One or more test cases do not belong to this project",
        );
      }
      if (input.testPlanId) {
        const plan = await db.testPlan.count({
          where: {
            id: input.testPlanId,
            projectId: id,
            workspaceId: access.workspaceId,
            deletedAt: null,
          },
        });
        if (!plan) throw new ApiError(400, "INVALID_TEST_PLAN", "Test plan is invalid");
      }
      const suite = await db.testSuite.create({
        data: {
          workspaceId: access.workspaceId,
          projectId: id,
          testPlanId: input.testPlanId,
          key: input.key ?? `SUITE-${Date.now().toString(36).toUpperCase()}`,
          name: input.name,
          description: input.description,
          createdById: auth(request).userId,
          updatedById: auth(request).userId,
          items: {
            create: input.testCaseIds.map((testCaseId, index) => ({
              workspaceId: access.workspaceId,
              testCaseId,
              position: index + 1,
              createdById: auth(request).userId,
            })),
          },
        },
        include: { items: true },
      });
      await audit(request, access.workspaceId, "suite.created", "TestSuite", suite.id);
      return reply.code(201).send(suite);
    },
  );

  app.post(
    "/api/v1/projects/:id/runs",
    { preHandler: authenticate, schema: { tags: ["runs"] } },
    async (request, reply) => {
      const { id } = IdParams.parse(request.params);
      const input = CreateRunSchema.parse(request.body);
      const access = await projectAccess(request, id, "test:execute");
      if (
        input.allowDestructive &&
        !hasPermission(access.role, "test:execute:destructive")
      ) {
        throw new ApiError(
          403,
          "FORBIDDEN",
          "Permission test:execute:destructive is required",
        );
      }
      const environment = await db.environment.findFirst({
        where: {
          id: input.environmentId,
          projectId: id,
          workspaceId: access.workspaceId,
          deletedAt: null,
        },
      });
      if (!environment) {
        throw new ApiError(400, "INVALID_ENVIRONMENT", "Environment is invalid");
      }
      let testCaseIds = input.testCaseIds ?? [];
      if (input.suiteId) {
        const suite = await db.testSuite.findFirst({
          where: {
            id: input.suiteId,
            projectId: id,
            workspaceId: access.workspaceId,
            deletedAt: null,
          },
          include: {
            items: {
              where: { enabled: true, testCase: { deletedAt: null } },
              select: { testCaseId: true },
            },
          },
        });
        if (!suite) throw new ApiError(400, "INVALID_SUITE", "Suite is invalid");
        testCaseIds = suite.items.map((item) => item.testCaseId);
      } else {
        const count = await db.testCase.count({
          where: {
            id: { in: testCaseIds },
            projectId: id,
            workspaceId: access.workspaceId,
            deletedAt: null,
          },
        });
        if (count !== testCaseIds.length) {
          throw new ApiError(
            400,
            "INVALID_TEST_CASES",
            "One or more test cases are invalid",
          );
        }
      }
      if (testCaseIds.length === 0) {
        throw new ApiError(400, "EMPTY_RUN", "A run must contain at least one test");
      }
      const run = await db.testRun.create({
        data: {
          workspaceId: access.workspaceId,
          projectId: id,
          testSuiteId: input.suiteId,
          environmentId: input.environmentId,
          createdById: auth(request).userId,
          status: "QUEUED",
          trigger: "MANUAL",
          totalTests: testCaseIds.length,
          config: json({
            testCaseIds,
            browsers: input.browsers,
            allowDestructive: input.allowDestructive,
            approvalTokenPresent: Boolean(input.approvalToken),
            correlationId: request.id,
          }),
        },
      });
      try {
        await queue.add(
          "execute-run",
          {
            runId: run.id,
            workspaceId: access.workspaceId,
            projectId: id,
            environmentId: input.environmentId,
            testCaseIds,
            correlationId: request.id,
          },
          run.id,
        );
      } catch (error) {
        request.log.error({ err: error, runId: run.id }, "Failed to enqueue run");
        throw new ApiError(
          503,
          "QUEUE_UNAVAILABLE",
          `Run ${run.id} was persisted but could not be enqueued`,
        );
      }
      await audit(request, access.workspaceId, "run.queued", "TestRun", run.id);
      await queue.publishRunEvent(run.id, {
        type: "run.queued",
        runId: run.id,
        status: run.status,
        at: new Date().toISOString(),
      });
      return reply.code(202).send(run);
    },
  );

  app.get(
    "/api/v1/runs/:id",
    { preHandler: authenticate, schema: { tags: ["runs"] } },
    async (request) => {
      const { id } = IdParams.parse(request.params);
      const run = await db.testRun.findFirst({
        where: {
          id,
          workspace: {
            memberships: {
              some: { userId: auth(request).userId, deletedAt: null },
            },
          },
        },
        include: {
          environment: { select: { id: true, name: true, kind: true } },
          testSuite: { select: { id: true, name: true } },
          attempts: true,
          results: true,
        },
      });
      if (!run) throw new ApiError(404, "NOT_FOUND", "Run was not found");
      await projectAccess(request, run.projectId, "run:read");
      return run;
    },
  );

  app.get(
    "/api/v1/runs/:id/events",
    { preHandler: authenticate, schema: { tags: ["runs"] } },
    async (request, reply) => {
      const { id } = IdParams.parse(request.params);
      const run = await db.testRun.findFirst({
        where: {
          id,
          workspace: {
            memberships: {
              some: { userId: auth(request).userId, deletedAt: null },
            },
          },
        },
      });
      if (!run) throw new ApiError(404, "NOT_FOUND", "Run was not found");
      await projectAccess(request, run.projectId, "run:read");
      const unsubscribe = await queue.subscribeToRun(id, (event) => {
        reply.raw.write(`event: run-update\ndata: ${event}\n\n`);
      });
      reply.hijack();
      reply.raw.writeHead(200, {
        "content-type": "text/event-stream",
        "cache-control": "no-cache, no-transform",
        connection: "keep-alive",
        "x-correlation-id": request.id,
      });
      reply.raw.write(
        `event: connected\ndata: ${JSON.stringify({ runId: id, status: run.status })}\n\n`,
      );
      const heartbeat = setInterval(() => {
        reply.raw.write(`: heartbeat ${Date.now()}\n\n`);
      }, 15_000);
      request.raw.once("close", () => {
        clearInterval(heartbeat);
        void unsubscribe();
      });
    },
  );

  app.post(
    "/api/v1/runs/:id/cancel",
    { preHandler: authenticate, schema: { tags: ["runs"] } },
    async (request) => {
      const { id } = IdParams.parse(request.params);
      const run = await db.testRun.findFirst({
        where: {
          id,
          workspace: {
            memberships: {
              some: { userId: auth(request).userId, deletedAt: null },
            },
          },
        },
      });
      if (!run) throw new ApiError(404, "NOT_FOUND", "Run was not found");
      const access = await projectAccess(request, run.projectId, "run:cancel");
      if (isTerminalRunStatus(run.status as TestRunStatus)) {
        throw new ApiError(409, "RUN_TERMINAL", "A terminal run cannot be cancelled");
      }
      const status = transitionTestRun(
        run.status as TestRunStatus,
        "CANCELLED",
      ) as typeof run.status;
      const updated = await db.testRun.update({
        where: { id },
        data: { status, finishedAt: new Date(), version: { increment: 1 } },
      });
      await queue.remove(id);
      await queue.publishRunEvent(id, {
        type: "run.cancelled",
        runId: id,
        status,
        at: new Date().toISOString(),
      });
      await audit(request, access.workspaceId, "run.cancelled", "TestRun", id);
      return updated;
    },
  );

  app.get(
    "/api/v1/projects/:id/failure-analyses",
    { preHandler: authenticate, schema: { tags: ["failures"] } },
    async (request) => {
      const { id } = IdParams.parse(request.params);
      const access = await projectAccess(request, id, "run:read");
      return db.failureAnalysis.findMany({
        where: {
          workspaceId: access.workspaceId,
          testResult: { testRun: { projectId: id } },
        },
        include: {
          testResult: {
            include: {
              testCase: { select: { id: true, key: true, title: true } },
              testRun: { select: { id: true, status: true, createdAt: true } },
            },
          },
          healingProposals: true,
        },
        orderBy: { createdAt: "desc" },
      });
    },
  );

  app.get(
    "/api/v1/projects/:id/healing-proposals",
    { preHandler: authenticate, schema: { tags: ["healing"] } },
    async (request) => {
      const { id } = IdParams.parse(request.params);
      const access = await projectAccess(request, id);
      return db.healingProposal.findMany({
        where: { projectId: id, workspaceId: access.workspaceId },
        include: {
          testCase: { select: { id: true, key: true, title: true, status: true } },
          failureAnalysis: true,
        },
        orderBy: { createdAt: "desc" },
      });
    },
  );

  async function decideHealing(
    request: FastifyRequest,
    decisionFromRoute?: "APPROVE" | "REJECT",
  ) {
    const { id } = IdParams.parse(request.params);
    const input = HealingDecisionInput.parse(request.body ?? {});
    const decision =
      decisionFromRoute ??
      ("decision" in input ? input.decision : undefined);
    if (!decision) {
      throw new ApiError(400, "DECISION_REQUIRED", "A healing decision is required");
    }
    const proposal = await db.healingProposal.findFirst({
      where: {
        id,
        project: {
          workspace: {
            memberships: {
              some: { userId: auth(request).userId, deletedAt: null },
            },
          },
        },
      },
    });
    if (!proposal) {
      throw new ApiError(404, "NOT_FOUND", "Healing proposal was not found");
    }
    await projectAccess(request, proposal.projectId, "healing:approve");
    if (proposal.status !== "PENDING") {
      throw new ApiError(409, "ALREADY_REVIEWED", "Proposal was already reviewed");
    }
    const note = "note" in input ? input.note : undefined;
    const updated = await db.healingProposal.update({
      where: { id },
      data: {
        status: decision === "APPROVE" ? "APPROVED" : "REJECTED",
        reviewComment: note,
        reviewedAt: new Date(),
        reviewedById: auth(request).userId,
        version: { increment: 1 },
      },
    });
    await audit(
      request,
      proposal.workspaceId,
      `healing.${decision.toLowerCase()}`,
      "HealingProposal",
      id,
      { note },
    );
    return updated;
  }

  app.post(
    "/api/v1/healing-proposals/:id/decision",
    { preHandler: authenticate, schema: { tags: ["healing"] } },
    (request) => decideHealing(request),
  );
  app.post(
    "/api/v1/healing-proposals/:id/approve",
    { preHandler: authenticate, schema: { tags: ["healing"] } },
    (request) => decideHealing(request, "APPROVE"),
  );
  app.post(
    "/api/v1/healing-proposals/:id/reject",
    { preHandler: authenticate, schema: { tags: ["healing"] } },
    (request) => decideHealing(request, "REJECT"),
  );

  app.get(
    "/api/v1/workspaces/:id/ai-configurations",
    { preHandler: authenticate, schema: { tags: ["ai-config"] } },
    async (request) => {
      const { id } = IdParams.parse(request.params);
      await workspaceAccess(request, id);
      return db.aiConfiguration.findMany({
        where: { workspaceId: id, deletedAt: null },
        select: {
          id: true,
          name: true,
          provider: true,
          model: true,
          settings: true,
          enabled: true,
          projectId: true,
          createdAt: true,
          updatedAt: true,
        },
        orderBy: { name: "asc" },
      });
    },
  );

  app.put(
    "/api/v1/workspaces/:id/ai-configurations",
    { preHandler: authenticate, schema: { tags: ["ai-config"] } },
    async (request) => {
      const { id } = IdParams.parse(request.params);
      const input = UpsertAiConfigurationSchema.parse(request.body);
      await workspaceAccess(request, id, "ai:configure");
      let encryptedCredentials: Prisma.InputJsonValue | undefined;
      if (input.apiKey) {
        if (!config.ENCRYPTION_KEY) {
          throw new ApiError(
            503,
            "ENCRYPTION_NOT_CONFIGURED",
            "ENCRYPTION_KEY is required to save provider credentials",
          );
        }
        encryptedCredentials = json(
          new SecretBox(config.ENCRYPTION_KEY).encrypt(input.apiKey),
        );
      }
      const configuration = await db.aiConfiguration.upsert({
        where: { workspaceId_name: { workspaceId: id, name: "Default" } },
        create: {
          workspaceId: id,
          name: "Default",
          provider: aiProviderKind(input.provider),
          model: input.modelId,
          encryptedCredentials,
          settings: json({
            baseUrl: input.baseUrl,
            isDefault: input.isDefault,
            maxTokens: input.maxTokens,
            temperature: input.temperature,
          }),
          createdById: auth(request).userId,
          updatedById: auth(request).userId,
        },
        update: {
          provider: aiProviderKind(input.provider),
          model: input.modelId,
          ...(encryptedCredentials ? { encryptedCredentials } : {}),
          settings: json({
            baseUrl: input.baseUrl,
            isDefault: input.isDefault,
            maxTokens: input.maxTokens,
            temperature: input.temperature,
          }),
          enabled: true,
          deletedAt: null,
          updatedById: auth(request).userId,
        },
        select: {
          id: true,
          name: true,
          provider: true,
          model: true,
          settings: true,
          enabled: true,
          updatedAt: true,
        },
      });
      await audit(
        request,
        id,
        "ai_configuration.updated",
        "AiConfiguration",
        configuration.id,
      );
      return configuration;
    },
  );

  app.get(
    "/api/v1/workspaces/:id/members",
    { preHandler: authenticate, schema: { tags: ["members"] } },
    async (request) => {
      const { id } = IdParams.parse(request.params);
      await workspaceAccess(request, id);
      return db.membership.findMany({
        where: { workspaceId: id, deletedAt: null, user: { deletedAt: null } },
        select: {
          id: true,
          role: true,
          createdAt: true,
          user: {
            select: { id: true, email: true, displayName: true, active: true },
          },
        },
        orderBy: { createdAt: "asc" },
      });
    },
  );

  app.get(
    "/api/v1/workspaces/:id/audit-log",
    { preHandler: authenticate, schema: { tags: ["audit"] } },
    async (request) => {
      const { id } = IdParams.parse(request.params);
      await workspaceAccess(request, id, "audit:read");
      const pagination = PaginationSchema.parse(request.query);
      const [items, total] = await Promise.all([
        db.auditEvent.findMany({
          where: { workspaceId: id },
          include: {
            actor: { select: { id: true, email: true, displayName: true } },
          },
          skip: (pagination.page - 1) * pagination.pageSize,
          take: pagination.pageSize,
          orderBy: { createdAt: "desc" },
        }),
        db.auditEvent.count({ where: { workspaceId: id } }),
      ]);
      return { items, total, ...pagination };
    },
  );

  app.get(
    "/api/v1/projects/:id/coverage-matrix",
    { preHandler: authenticate, schema: { tags: ["coverage"] } },
    async (request) => {
      const { id } = IdParams.parse(request.params);
      const access = await projectAccess(request, id);
      const requirements = await db.requirement.findMany({
        where: { projectId: id, workspaceId: access.workspaceId, deletedAt: null },
        include: {
          testCases: {
            where: { deletedAt: null },
            include: {
              testResults: {
                orderBy: { createdAt: "desc" },
                take: 1,
                select: { outcome: true, createdAt: true, testRunId: true },
              },
            },
          },
        },
        orderBy: { key: "asc" },
      });
      const matrix = requirements.map((requirement) => {
        const outcomes = requirement.testCases.flatMap((testCase) =>
          testCase.testResults.map((result) => result.outcome),
        );
        const status =
          requirement.testCases.length === 0
            ? "NOT_COVERED"
            : outcomes.includes("FAILED")
              ? "COVERED_FAILING"
              : outcomes.includes("PASSED")
                ? "COVERED_PASSING"
                : "COVERED_NOT_EXECUTED";
        return {
          requirement: {
            id: requirement.id,
            key: requirement.key,
            title: requirement.title,
            riskLevel: requirement.riskLevel,
          },
          status,
          testCases: requirement.testCases.map((testCase) => ({
            id: testCase.id,
            key: testCase.key,
            title: testCase.title,
            status: testCase.status,
            latestResult: testCase.testResults[0] ?? null,
          })),
        };
      });
      return {
        matrix,
        summary: {
          requirements: matrix.length,
          covered: matrix.filter((item) => item.status !== "NOT_COVERED").length,
        },
      };
    },
  );

  app.get(
    "/api/v1/projects/:id/application-maps",
    { preHandler: authenticate, schema: { tags: ["application-maps"] } },
    async (request) => {
      const { id } = IdParams.parse(request.params);
      const access = await projectAccess(request, id);
      return db.applicationMap.findMany({
        where: { projectId: id, workspaceId: access.workspaceId, deletedAt: null },
        include: {
          environment: { select: { id: true, name: true, kind: true } },
        },
        orderBy: { generatedAt: "desc" },
      });
    },
  );

  app.setNotFoundHandler(async (request) => {
    throw new ApiError(
      404,
      "ROUTE_NOT_FOUND",
      `Route ${request.method} ${request.url} was not found`,
    );
  });
  app.setErrorHandler(
    async (error: Error & { code?: string; statusCode?: number }, request, reply) => {
      if (error instanceof ZodError) {
        return reply.code(400).send({
          error: {
            code: "VALIDATION_ERROR",
            message: "Request validation failed",
            details: error.issues,
            correlationId: request.id,
          },
        });
      }
      if (error instanceof ApiError) {
        return reply.code(error.statusCode).send({
          error: {
            code: error.code,
            message: error.message,
            correlationId: request.id,
          },
        });
      }
      if (error.code === "P2002") {
        return reply.code(409).send({
          error: {
            code: "CONFLICT",
            message: "A record with the same unique key already exists",
            correlationId: request.id,
          },
        });
      }
      request.log.error({ err: error }, "Unhandled API error");
      return reply.code(error.statusCode ?? 500).send({
        error: {
          code: error.code ?? "INTERNAL_ERROR",
          message:
            config.NODE_ENV === "production"
              ? "An internal error occurred"
              : error.message,
          correlationId: request.id,
        },
      });
    },
  );

  app.addHook("onClose", async () => {
    s3.destroy();
    if (ownsQueue) await queue.close();
  });

  await app.ready();
  return app;
}

export { InMemoryJobQueue };
